<Project Sdk="Aspire.AppHost.Sdk/13.1.3">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>be7b033f-639c-4c26-9bb2-f57195ce134a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CosmicChimps.Aspire.Hosting.Dokploy\CosmicChimps.Aspire.Hosting.Dokploy.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\CosmicChimps.Aspire.ApiService\CosmicChimps.Aspire.ApiService.csproj" />
    <ProjectReference Include="..\CosmicChimps.Aspire.Web\CosmicChimps.Aspire.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" Version="13.2.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.2.0" />
    <PackageReference Include="Aspire.Hosting.Seq" Version="13.2.0" />
  </ItemGroup>
</Project>
